export type ExpertCommand = {
  trigger: string
  description: string
}

export type ExpertDataConnection = {
  name: string
  description: string
  enabled: boolean
}

export type ExpertKnowledgeModule = {
  title: string
  description: string
}

export type ExpertSuite = {
  id: string
  name: string
  author: string
  category: '总控管理' | '空间分析' | '遥感解译' | '数据处理' | '专题制图' | '灾害评估' | '工程开发' | '学术写作'
  description: string
  version: string
  commandCount: number
  knowledgeCount: number
  installed: boolean
  featured?: boolean
  quickCommands: ExpertCommand[]
  dataConnections: ExpertDataConnection[]
  knowledgeModules: ExpertKnowledgeModule[]
}

export const mockExpertSuites: ExpertSuite[] = [
  {
    id: 'spatial-analyst',
    name: '空间分析规划师',
    author: '@GeoWork',
    category: '空间分析',
    description: '面向缓冲区、叠加分析、可达性评估和选址分析的 GIS 工作流专家。',
    version: 'v1.0.0',
    commandCount: 5,
    knowledgeCount: 4,
    installed: true,
    featured: true,
    quickCommands: [
      { trigger: '/缓冲区分析', description: '对指定要素生成缓冲区' },
      { trigger: '/叠加分析', description: '多图层叠加计算' },
      { trigger: '/选址评估', description: '综合因子选址评分' },
      { trigger: '/可达性分析', description: '服务可达性评估' },
      { trigger: '/空间查询', description: '按条件查询空间要素' },
    ],
    dataConnections: [
      { name: '当前工作目录', description: '访问工作区中的矢量数据', enabled: true },
      { name: '空间数据索引', description: '自动索引 GeoJSON/Shapefile', enabled: true },
    ],
    knowledgeModules: [
      { title: '坐标系统与投影', description: '常见坐标系、投影变换、EPSG 编码' },
      { title: '缓冲区与叠加分析', description: '缓冲区生成策略、多图层叠加算法' },
      { title: '可达性模型', description: '服务半径、网络分析、OD 矩阵' },
      { title: '选址评估方法', description: '多因子加权评分、AHP 层次分析' },
    ],
  },
  {
    id: 'remote-sensing',
    name: '遥感解译助手',
    author: '@GeoWork',
    category: '遥感解译',
    description: '辅助进行 NDVI、土地覆盖识别、变化检测和遥感影像解译。',
    version: 'v1.0.0',
    commandCount: 5,
    knowledgeCount: 3,
    installed: false,
    quickCommands: [
      { trigger: '/NDVI计算', description: '计算归一化植被指数' },
      { trigger: '/土地覆盖解译', description: '土地覆盖类型识别' },
      { trigger: '/变化检测', description: '多期影像变化检测' },
      { trigger: '/云量检查', description: '检查影像云量覆盖' },
      { trigger: '/影像预处理', description: '辐射校正与几何校正' },
    ],
    dataConnections: [
      { name: '遥感影像目录', description: '访问工作区中的遥感影像', enabled: true },
      { name: '当前工作目录', description: '访问工作区中的文件', enabled: true },
    ],
    knowledgeModules: [
      { title: '遥感指数与变化检测', description: 'NDVI、NDWI、NDBI 等常用指数' },
      { title: '土地覆盖分类', description: '监督分类、非监督分类方法' },
      { title: '影像预处理', description: '大气校正、几何校正、融合' },
    ],
  },
  {
    id: 'data-qc',
    name: '空间数据质检员',
    author: '@GeoWork',
    category: '数据处理',
    description: '检查 GeoJSON、Shapefile、CSV 坐标字段、几何有效性和坐标系统一致性。',
    version: 'v1.0.0',
    commandCount: 5,
    knowledgeCount: 3,
    installed: false,
    quickCommands: [
      { trigger: '/检查坐标系', description: '验证坐标系统声明' },
      { trigger: '/检查几何错误', description: '检查自相交、空几何等' },
      { trigger: '/字段完整性检查', description: '检查必填字段缺失' },
      { trigger: '/重复要素检查', description: '检测重复几何要素' },
      { trigger: '/导出质检报告', description: '生成质检结果报告' },
    ],
    dataConnections: [
      { name: '当前工作目录', description: '访问工作区中的数据文件', enabled: true },
    ],
    knowledgeModules: [
      { title: '数据质量检查', description: '几何有效性、属性完整性、拓扑关系' },
      { title: '坐标系统与投影', description: '坐标系声明、投影一致性验证' },
      { title: '质检报告规范', description: '报告格式、统计口径、问题分级' },
    ],
  },
  {
    id: 'thematic-cartographer',
    name: '专题地图制图师',
    author: '@GeoWork',
    category: '专题制图',
    description: '根据业务目标生成专题地图设计建议、图例规范、配色方案和出图说明。',
    version: 'v1.0.0',
    commandCount: 5,
    knowledgeCount: 4,
    installed: false,
    quickCommands: [
      { trigger: '/生成专题图', description: '根据数据生成专题地图' },
      { trigger: '/设计图例', description: '生成图例规范建议' },
      { trigger: '/地图配色', description: '推荐配色方案' },
      { trigger: '/出图检查', description: '检查出图规范合规性' },
      { trigger: '/制图说明', description: '生成制图技术说明' },
    ],
    dataConnections: [
      { name: '当前工作目录', description: '访问工作区中的地图数据', enabled: true },
      { name: '空间数据索引', description: '自动索引矢量数据', enabled: true },
    ],
    knowledgeModules: [
      { title: '专题制图规范', description: '图例、比例尺、指北针、注记' },
      { title: '配色方案', description: '分类色、渐变、色盲友好配色' },
      { title: '符号化策略', description: '点、线、面要素符号化' },
      { title: '出图格式', description: 'PNG、PDF、SVG 输出规范' },
    ],
  },
  {
    id: 'urban-renewal',
    name: '城市更新评估专家',
    author: '@GeoWork',
    category: '空间分析',
    description: '面向城市更新、人口服务半径、公共设施覆盖和地块潜力评估的分析专家。',
    version: 'v1.0.0',
    commandCount: 5,
    knowledgeCount: 4,
    installed: false,
    quickCommands: [
      { trigger: '/设施覆盖分析', description: '分析公共设施空间覆盖' },
      { trigger: '/服务半径评估', description: '评估设施服务半径' },
      { trigger: '/地块潜力评分', description: '地块开发潜力综合评分' },
      { trigger: '/人口可达性', description: '人口分布与设施可达性' },
      { trigger: '/更新单元识别', description: '识别城市更新单元' },
    ],
    dataConnections: [
      { name: '当前工作目录', description: '访问工作区中的城市数据', enabled: true },
      { name: '空间数据索引', description: '索引 POI、建筑、地块数据', enabled: true },
    ],
    knowledgeModules: [
      { title: '城市更新政策', description: '更新单元划定、容积率、用地性质' },
      { title: '公共服务设施标准', description: '教育、医疗、交通服务半径' },
      { title: '地块评估方法', description: '潜力评分、区位因子、交通可达性' },
      { title: '人口空间分析', description: '人口密度、服务覆盖、供需匹配' },
    ],
  },
  {
    id: 'disaster-risk',
    name: '灾害风险评估专家',
    author: '@GeoWork',
    category: '灾害评估',
    description: '辅助进行洪涝、滑坡、火灾等风险因子叠加分析和应急地图生成。',
    version: 'v1.0.0',
    commandCount: 5,
    knowledgeCount: 4,
    installed: false,
    quickCommands: [
      { trigger: '/风险因子叠加', description: '多因子风险叠加分析' },
      { trigger: '/洪涝影响范围', description: '洪涝淹没范围模拟' },
      { trigger: '/应急地图生成', description: '生成应急响应地图' },
      { trigger: '/风险分区', description: '风险等级空间分区' },
      { trigger: '/灾害报告摘要', description: '生成灾害风险评估报告' },
    ],
    dataConnections: [
      { name: '当前工作目录', description: '访问工作区中的灾害数据', enabled: true },
      { name: '遥感影像目录', description: '访问遥感监测数据', enabled: true },
      { name: '空间数据索引', description: '索引 DEM、水系、地质数据', enabled: true },
    ],
    knowledgeModules: [
      { title: '灾害风险模型', description: '洪涝、滑坡、火灾风险评估方法' },
      { title: '应急响应规范', description: '应急地图、疏散路线、避难场所' },
      { title: '风险分区方法', description: '风险等级划分、敏感性分析' },
      { title: '灾害报告模板', description: '报告结构、统计口径、建议措施' },
    ],
  },
  {
    id: 'dem-analysis',
    name: 'DEM 地形分析专家',
    author: '@GeoWork',
    category: '空间分析',
    description: '面向 DEM 数据的坡度、坡向、汇流、剖面和地形因子分析。',
    version: 'v1.0.0',
    commandCount: 5,
    knowledgeCount: 3,
    installed: false,
    quickCommands: [
      { trigger: '/坡度分析', description: '计算坡度栅格' },
      { trigger: '/坡向分析', description: '计算坡向栅格' },
      { trigger: '/流域提取', description: '流域边界与河网提取' },
      { trigger: '/剖面分析', description: '地形剖面线分析' },
      { trigger: '/地形因子统计', description: '地形因子统计汇总' },
    ],
    dataConnections: [
      { name: '当前工作目录', description: '访问工作区中的 DEM 数据', enabled: true },
      { name: '空间数据索引', description: '索引高程栅格数据', enabled: true },
    ],
    knowledgeModules: [
      { title: '地形分析方法', description: '坡度、坡向、曲率、汇流累积' },
      { title: '流域提取算法', description: 'D8 算法、河网分级、流域划分' },
      { title: '地形因子', description: '地形湿度指数、地形位置指数' },
    ],
  },
  {
    id: 'change-detection',
    name: '遥感变化监测专家',
    author: '@GeoWork',
    category: '遥感解译',
    description: '面向多期遥感影像的变化检测、异常区域标记和变化摘要生成。',
    version: 'v1.0.0',
    commandCount: 5,
    knowledgeCount: 3,
    installed: false,
    quickCommands: [
      { trigger: '/多期影像对比', description: '多时相影像对比分析' },
      { trigger: '/变化区域提取', description: '提取变化图斑' },
      { trigger: '/异常斑块标记', description: '标记异常变化区域' },
      { trigger: '/变化面积统计', description: '统计变化面积与类型' },
      { trigger: '/监测报告生成', description: '生成变化监测报告' },
    ],
    dataConnections: [
      { name: '遥感影像目录', description: '访问多期遥感影像', enabled: true },
      { name: '当前工作目录', description: '访问工作区中的矢量数据', enabled: true },
    ],
    knowledgeModules: [
      { title: '变化检测方法', description: '影像差值、分类后比较、对象级检测' },
      { title: '变化类型体系', description: '土地利用变化分类、转移矩阵' },
      { title: '监测报告模板', description: '报告结构、图表规范、变化摘要' },
    ],
  },
  {
    id: 'master-controller',
    name: '总控专家',
    author: '@GeoWork',
    category: '总控管理',
    description: '协调多专家协作，负责任务分发、进度跟踪和结果汇总的全局管控专家。',
    version: 'v1.0.0',
    commandCount: 5,
    knowledgeCount: 3,
    installed: false,
    quickCommands: [
      { trigger: '/任务分发', description: '将复杂任务拆解并分配给子专家' },
      { trigger: '/进度总览', description: '查看各专家执行进度与状态' },
      { trigger: '/结果汇总', description: '汇总各专家产出并生成综合报告' },
      { trigger: '/冲突检测', description: '检测多专家输出间的矛盾与冲突' },
      { trigger: '/流程回退', description: '回退到指定步骤重新执行' },
    ],
    dataConnections: [
      { name: '专家执行记录', description: '访问所有子专家的执行日志', enabled: true },
      { name: '当前工作目录', description: '访问工作区中的全部文件', enabled: true },
    ],
    knowledgeModules: [
      { title: '多智能体协作模式', description: '任务编排、角色分工、结果聚合' },
      { title: '工作流状态机', description: '流程控制、分支决策、异常回退' },
      { title: '质量门控策略', description: '阶段检查点、验收标准、自动审批' },
    ],
  },
  {
    id: 'paper-advisor',
    name: '论文专家',
    author: '@GeoWork',
    category: '学术写作',
    description: '面向地学学术论文的选题建议、文献综述、方法论设计和审稿意见分析。',
    version: 'v1.0.0',
    commandCount: 5,
    knowledgeCount: 4,
    installed: false,
    quickCommands: [
      { trigger: '/选题建议', description: '根据研究方向生成选题建议' },
      { trigger: '/文献综述', description: '整理相关文献并生成综述框架' },
      { trigger: '/方法论设计', description: '建议研究方法与实验设计' },
      { trigger: '/审稿意见分析', description: '分析审稿意见并给出修改建议' },
      { trigger: '/论文结构优化', description: '优化论文整体结构与逻辑链' },
    ],
    dataConnections: [
      { name: '当前工作目录', description: '访问工作区中的论文草稿', enabled: true },
    ],
    knowledgeModules: [
      { title: '地学论文结构', description: 'IMRaD 结构、摘要写作、关键词选取' },
      { title: '文献管理', description: '引用格式、文献检索策略、综述方法' },
      { title: '研究方法论', description: '定量/定性方法、实验设计、统计检验' },
      { title: '审稿回复规范', description: '逐条回复策略、语气措辞、修改标注' },
    ],
  },
  {
    id: 'data-specialist',
    name: '数据专家',
    author: '@GeoWork',
    category: '数据处理',
    description: '面向空间数据清洗、格式转换、坐标系转换和数据融合的全流程数据处理专家。',
    version: 'v1.0.0',
    commandCount: 5,
    knowledgeCount: 3,
    installed: false,
    quickCommands: [
      { trigger: '/数据清洗', description: '去除重复、修复几何、标准化字段' },
      { trigger: '/格式转换', description: 'GeoJSON/Shapefile/CSV 互转' },
      { trigger: '/坐标转换', description: '坐标系转换与投影重定义' },
      { trigger: '/数据融合', description: '多源数据空间连接与属性关联' },
      { trigger: '/数据统计', description: '生成数据分布与统计摘要' },
    ],
    dataConnections: [
      { name: '当前工作目录', description: '访问工作区中的数据文件', enabled: true },
      { name: '空间数据索引', description: '自动索引矢量与栅格数据', enabled: true },
    ],
    knowledgeModules: [
      { title: '空间数据格式', description: 'GeoJSON、Shapefile、GeoTIFF、GeoPackage' },
      { title: '数据清洗策略', description: '去重、修复拓扑、字段标准化' },
      { title: '坐标系与投影', description: 'EPSG 编码、WGS84、常用投影选择' },
    ],
  },
  {
    id: 'gee-specialist',
    name: 'GEE 专家',
    author: '@GeoWork',
    category: '工程开发',
    description: '面向 Google Earth Engine 平台的 JavaScript/Python 脚本编写、影像集合处理和时序分析。',
    version: 'v1.0.0',
    commandCount: 5,
    knowledgeCount: 4,
    installed: false,
    quickCommands: [
      { trigger: '/GEE脚本生成', description: '生成 Earth Engine 分析脚本' },
      { trigger: '/影像集合筛选', description: '按时间、区域、云量筛选影像' },
      { trigger: '/时序分析', description: '构建 NDVI/EVI 时序曲线' },
      { trigger: '/导出到Drive', description: '将计算结果导出到 Google Drive' },
      { trigger: '/GEE调试', description: '排查常见 GEE 脚本错误' },
    ],
    dataConnections: [
      { name: 'GEE 资产目录', description: '访问 Earth Engine 资产列表', enabled: true },
      { name: '当前工作目录', description: '访问工作区中的脚本文件', enabled: true },
    ],
    knowledgeModules: [
      { title: 'Earth Engine API', description: 'ee.Image、ee.FeatureCollection、Reducer' },
      { title: '遥感指数计算', description: 'NDVI、EVI、NDWI 在 GEE 中的实现' },
      { title: '时序与趋势分析', description: 'Harmonic 模型、Mann-Kendall 趋势检验' },
      { title: 'GEE 性能优化', description: '分块计算、并行化、export 策略' },
    ],
  },
  {
    id: 'qgis-specialist',
    name: 'QGIS 专家',
    author: '@GeoWork',
    category: '工程开发',
    description: '面向 QGIS 的 PyQGIS 脚本、Processing 模型、插件开发和项目配置管理。',
    version: 'v1.0.0',
    commandCount: 5,
    knowledgeCount: 4,
    installed: false,
    quickCommands: [
      { trigger: '/PyQGIS脚本', description: '生成 PyQGIS 自动化脚本' },
      { trigger: '/Processing模型', description: '创建 QGIS Processing 模型' },
      { trigger: '/样式配置', description: '生成 QML 样式文件' },
      { trigger: '/插件开发', description: 'QGIS 插件脚手架与开发指导' },
      { trigger: '/项目配置', description: '生成 .qgz 项目配置建议' },
    ],
    dataConnections: [
      { name: '当前工作目录', description: '访问工作区中的 QGIS 项目文件', enabled: true },
      { name: '空间数据索引', description: '索引矢量与栅格数据', enabled: true },
    ],
    knowledgeModules: [
      { title: 'PyQGIS API', description: 'QgsProject、QgsVectorLayer、Processing 框架' },
      { title: 'Processing 算法', description: '内置算法、SAGA、GRASS 集成' },
      { title: 'QGIS 样式系统', description: 'QML/QLR、分类渲染、规则渲染' },
      { title: '插件开发规范', description: 'Plugin Builder、信号槽、dockwidget' },
    ],
  },
  {
    id: 'remote-sensing-analysis',
    name: '遥感分析专家',
    author: '@GeoWork',
    category: '遥感解译',
    description: '面向遥感影像的定量分析，包括光谱指数计算、分类精度评估和地物光谱特征分析。',
    version: 'v1.0.0',
    commandCount: 5,
    knowledgeCount: 4,
    installed: false,
    quickCommands: [
      { trigger: '/光谱指数计算', description: '批量计算 NDVI/NDWI/NDBI 等指数' },
      { trigger: '/分类精度评估', description: '计算混淆矩阵与 Kappa 系数' },
      { trigger: '/地物光谱分析', description: '分析典型地物光谱反射特征' },
      { trigger: '/影像融合', description: '多源影像数据融合处理' },
      { trigger: '/时序变化分析', description: '多时相遥感数据变化趋势' },
    ],
    dataConnections: [
      { name: '遥感影像目录', description: '访问工作区中的遥感影像', enabled: true },
      { name: '当前工作目录', description: '访问工作区中的样本数据', enabled: true },
    ],
    knowledgeModules: [
      { title: '光谱指数体系', description: '植被指数、水体指数、建筑指数' },
      { title: '分类精度评估', description: '混淆矩阵、Kappa、OA、PA、UA' },
      { title: '地物光谱特征', description: '典型地物反射光谱、光谱库' },
      { title: '遥感定量分析', description: '辐射传输模型、大气校正方法' },
    ],
  },
  {
    id: 'gis-engineering',
    name: 'GIS 工程专家',
    author: '@GeoWork',
    category: '工程开发',
    description: '面向 GIS 软件工程的项目架构设计、空间数据库建模、服务部署和 CI/CD 配置。',
    version: 'v1.0.0',
    commandCount: 5,
    knowledgeCount: 4,
    installed: false,
    quickCommands: [
      { trigger: '/架构设计', description: 'GIS 系统架构方案建议' },
      { trigger: '/数据库建模', description: 'PostGIS 空间数据库设计' },
      { trigger: '/服务部署', description: 'GeoServer/MapServer 部署配置' },
      { trigger: '/API设计', description: 'RESTful 空间服务 API 设计' },
      { trigger: '/CI配置', description: 'GIS 项目 CI/CD 流水线配置' },
    ],
    dataConnections: [
      { name: '当前工作目录', description: '访问工作区中的项目代码', enabled: true },
      { name: '空间数据索引', description: '索引项目中的空间数据', enabled: true },
    ],
    knowledgeModules: [
      { title: 'GIS 系统架构', description: '微服务、空间数据管线、缓存策略' },
      { title: 'PostGIS 空间数据库', description: '空间索引、分区表、空间函数' },
      { title: '地图服务部署', description: 'GeoServer、MapServer、TileServer' },
      { title: 'GIS 开发规范', description: '代码结构、测试策略、文档规范' },
    ],
  },
  {
    id: 'map-cartography',
    name: '地图制图专家',
    author: '@GeoWork',
    category: '专题制图',
    description: '面向地图设计与制作的专家，涵盖地图投影选择、符号设计、图面平衡和印刷规范。',
    version: 'v1.0.0',
    commandCount: 5,
    knowledgeCount: 4,
    installed: false,
    quickCommands: [
      { trigger: '/地图设计', description: '根据数据特征推荐地图类型' },
      { trigger: '/符号设计', description: '生成要素符号化方案' },
      { trigger: '/图面布局', description: '推荐图面元素排布方案' },
      { trigger: '/印刷检查', description: '检查 DPI、出血线、色彩模式' },
      { trigger: '/交互式地图', description: '生成 Web 地图配置方案' },
    ],
    dataConnections: [
      { name: '当前工作目录', description: '访问工作区中的地图数据', enabled: true },
      { name: '空间数据索引', description: '索引矢量与栅格数据', enabled: true },
    ],
    knowledgeModules: [
      { title: '地图投影选择', description: '等面积、等角、等距投影适用场景' },
      { title: '符号与注记设计', description: '点/线/面符号、注记层次、视觉变量' },
      { title: '图面设计原则', description: '视觉平衡、图例设计、比例尺选择' },
      { title: '印刷与输出', description: 'DPI、CMYK/RGB、出血线、PDF/X' },
    ],
  },
  {
    id: 'lab-report',
    name: '实验报告专家',
    author: '@GeoWork',
    category: '学术写作',
    description: '面向地理信息科学实验报告的撰写，包括实验目的、方法、结果分析和图表生成。',
    version: 'v1.0.0',
    commandCount: 5,
    knowledgeCount: 3,
    installed: false,
    quickCommands: [
      { trigger: '/生成报告框架', description: '根据实验内容生成报告结构' },
      { trigger: '/结果分析', description: '分析实验数据并生成结论' },
      { trigger: '/图表生成', description: '生成实验结果可视化图表' },
      { trigger: '/方法描述', description: '撰写实验方法与步骤' },
      { trigger: '/报告润色', description: '优化报告语言与格式' },
    ],
    dataConnections: [
      { name: '当前工作目录', description: '访问工作区中的实验数据', enabled: true },
    ],
    knowledgeModules: [
      { title: '实验报告结构', description: '目的、原理、步骤、结果、讨论' },
      { title: '数据可视化规范', description: '图表类型选择、标注、配色' },
      { title: 'GIS 实验方法', description: '空间分析实验、遥感实验、数据库实验' },
    ],
  },
  {
    id: 'paper-writer',
    name: '论文写作专家',
    author: '@GeoWork',
    category: '学术写作',
    description: '面向地学论文的全流程写作辅助，从摘要到参考文献格式，确保学术规范与逻辑清晰。',
    version: 'v1.0.0',
    commandCount: 5,
    knowledgeCount: 4,
    installed: false,
    quickCommands: [
      { trigger: '/摘要写作', description: '根据论文内容生成结构化摘要' },
      { trigger: '/引言撰写', description: '撰写研究背景与问题提出' },
      { trigger: '/参考文献格式', description: '按指定格式生成参考文献列表' },
      { trigger: '/图表说明', description: '生成图表标题与注释说明' },
      { trigger: '/全文校对', description: '检查语法、术语一致性和格式规范' },
    ],
    dataConnections: [
      { name: '当前工作目录', description: '访问工作区中的论文文件', enabled: true },
    ],
    knowledgeModules: [
      { title: '学术写作规范', description: '学术语言、被动语态、逻辑连接词' },
      { title: '参考文献管理', description: 'APA/GB-T 7714 格式、DOI、交叉引用' },
      { title: '论文各章节写作', description: '摘要、引言、方法、结果、讨论' },
      { title: '投稿与修改', description: 'Cover Letter、审稿回复、修改标注' },
    ],
  },
  {
    id: 'quality-checker',
    name: '质量检查专家',
    author: '@GeoWork',
    category: '数据处理',
    description: '面向空间数据和成果产出的全面质量检查，包括拓扑校验、属性一致性和报告合规性。',
    version: 'v1.0.0',
    commandCount: 5,
    knowledgeCount: 3,
    installed: false,
    quickCommands: [
      { trigger: '/拓扑检查', description: '检查空间拓扑关系错误' },
      { trigger: '/属性一致性', description: '验证属性字段与值的一致性' },
      { trigger: '/精度评估', description: '评估空间数据精度与可靠性' },
      { trigger: '/成果检查', description: '检查最终产出是否符合验收标准' },
      { trigger: '/质检报告', description: '生成完整的质量检查报告' },
    ],
    dataConnections: [
      { name: '当前工作目录', description: '访问工作区中的数据和成果', enabled: true },
      { name: '空间数据索引', description: '索引待检查的空间数据', enabled: true },
    ],
    knowledgeModules: [
      { title: '拓扑规则', description: '重叠、间隙、悬挂线、自相交检查' },
      { title: '属性校验规则', description: '值域检查、逻辑一致性、关联校验' },
      { title: '质量评估标准', description: '精度等级、完整性、时效性评估' },
    ],
  },
  {
    id: 'code-reviewer',
    name: '代码审查专家',
    author: '@GeoWork',
    category: '工程开发',
    description: '面向 GIS 代码的审查与优化，包括代码质量评估、性能分析、安全检查和重构建议。',
    version: 'v1.0.0',
    commandCount: 5,
    knowledgeCount: 4,
    installed: false,
    quickCommands: [
      { trigger: '/代码审查', description: '对指定代码文件进行全面审查' },
      { trigger: '/性能分析', description: '分析空间算法性能瓶颈' },
      { trigger: '/安全检查', description: '检查代码中的安全漏洞' },
      { trigger: '/重构建议', description: '提出代码重构优化方案' },
      { trigger: '/测试建议', description: '生成单元测试与集成测试建议' },
    ],
    dataConnections: [
      { name: '当前工作目录', description: '访问工作区中的代码文件', enabled: true },
    ],
    knowledgeModules: [
      { title: '代码质量标准', description: 'SOLID 原则、代码复杂度、命名规范' },
      { title: '空间算法性能', description: '空间索引、批量处理、内存优化' },
      { title: '安全编码规范', description: 'SQL 注入、路径遍历、输入验证' },
      { title: '测试策略', description: '单元测试、集成测试、Mock 数据' },
    ],
  },
]

export const expertCategories = [
  '全部',
  '总控管理',
  '空间分析',
  '遥感解译',
  '数据处理',
  '专题制图',
  '灾害评估',
  '工程开发',
  '学术写作',
] as const
