/* ── MCP 服务 Mock 数据 ── */

export type McpCategory =
  | '数据库'
  | '地图服务'
  | '遥感平台'
  | '本地工具'
  | '文件系统'
  | '开发工具'
  | '自动报告'

export type McpTransport = 'stdio' | 'http' | 'sse' | 'websocket'

export type McpSource = 'market' | 'built-in' | 'local'

export type McpStatus = 'not-connected' | 'connected' | 'disabled' | 'error'

export type McpServerItem = {
  id: string
  name: string
  slug: string
  author: string
  category: McpCategory
  source: McpSource
  description: string
  version: string
  transport: McpTransport
  endpoint?: string
  command?: string
  args?: string[]
  env?: Record<string, string>
  downloads?: string
  connected: boolean
  enabled: boolean
  status: McpStatus
  featured?: boolean
  tags: string[]
  tools: string[]
}

export const mcpCategories = [
  '全部',
  '数据库',
  '地图服务',
  '遥感平台',
  '本地工具',
  '文件系统',
  '开发工具',
  '自动报告',
]

/* ── 市场 MCP（12个） ── */

export const marketMcpServers: McpServerItem[] = [
  {
    id: 'postgis-query',
    name: 'PostGIS 查询服务',
    slug: 'postgis-query',
    author: '@GeoWork',
    category: '数据库',
    source: 'market',
    description: '连接 PostGIS 数据库，查询空间表、字段、几何类型和范围统计。',
    version: 'v1.2.0',
    transport: 'stdio',
    downloads: '31.2K',
    connected: false,
    enabled: false,
    status: 'not-connected',
    featured: true,
    tags: ['PostGIS', '空间查询', '数据库'],
    tools: ['list_tables', 'describe_layer', 'spatial_query'],
  },
  {
    id: 'geoserver-layers',
    name: 'GeoServer 图层服务',
    slug: 'geoserver-layers',
    author: '@GeoWork',
    category: '地图服务',
    source: 'market',
    description: '读取 GeoServer 工作区、图层、样式和 WMS/WFS 服务能力。',
    version: 'v1.1.0',
    transport: 'http',
    downloads: '25.6K',
    connected: false,
    enabled: false,
    status: 'not-connected',
    tags: ['GeoServer', 'WMS', 'WFS'],
    tools: ['list_workspaces', 'list_layers', 'get_wms_capabilities'],
  },
  {
    id: 'qgis-processing',
    name: 'QGIS Processing',
    slug: 'qgis-processing',
    author: '@GeoWork',
    category: '本地工具',
    source: 'market',
    description: '调用 QGIS Processing 算法执行缓冲区、裁剪、叠加和栅格分析。',
    version: 'v1.0.2',
    transport: 'stdio',
    downloads: '22.8K',
    connected: false,
    enabled: false,
    status: 'not-connected',
    tags: ['QGIS', '空间分析', '算法'],
    tools: ['list_algorithms', 'run_processing', 'export_result'],
  },
  {
    id: 'gdal-toolbox',
    name: 'GDAL 工具箱',
    slug: 'gdal-toolbox',
    author: '@GeoWork',
    category: '本地工具',
    source: 'market',
    description: '通过 GDAL / OGR 读取矢量与栅格元数据，转换格式和坐标系。',
    version: 'v1.0.3',
    transport: 'stdio',
    downloads: '20.3K',
    connected: false,
    enabled: false,
    status: 'not-connected',
    tags: ['GDAL', 'OGR', '坐标转换'],
    tools: ['ogr_info', 'gdal_info', 'transform_dataset'],
  },
  {
    id: 'sentinel-hub-search',
    name: 'Sentinel Hub 影像检索',
    slug: 'sentinel-hub-search',
    author: '@GeoWork',
    category: '遥感平台',
    source: 'market',
    description: '检索 Sentinel 影像、云量、时间范围和波段信息。',
    version: 'v1.3.0',
    transport: 'http',
    downloads: '18.7K',
    connected: false,
    enabled: false,
    status: 'not-connected',
    tags: ['Sentinel', '遥感影像', '云量'],
    tools: ['search_imagery', 'inspect_bands', 'download_preview'],
  },
  {
    id: 'arcgis-rest',
    name: 'ArcGIS REST 服务',
    slug: 'arcgis-rest',
    author: '@GeoWork',
    category: '地图服务',
    source: 'market',
    description: '接入 ArcGIS REST 图层，查询要素、字段和服务元信息。',
    version: 'v1.0.0',
    transport: 'http',
    downloads: '16.4K',
    connected: false,
    enabled: false,
    status: 'not-connected',
    tags: ['ArcGIS', 'REST', '要素查询'],
    tools: ['list_services', 'query_features', 'describe_service'],
  },
  {
    id: 'osm-overpass',
    name: 'OSM Overpass 查询',
    slug: 'osm-overpass',
    author: '@GeoWork',
    category: '地图服务',
    source: 'market',
    description: '根据区域和标签查询 OpenStreetMap POI、道路和建筑物数据。',
    version: 'v1.1.2',
    transport: 'http',
    downloads: '15.1K',
    connected: false,
    enabled: false,
    status: 'not-connected',
    tags: ['OSM', 'POI', 'Overpass'],
    tools: ['query_osm', 'summarize_poi'],
  },
  {
    id: 'cesium-tiles',
    name: 'Cesium 3D Tiles',
    slug: 'cesium-tiles',
    author: '@GeoWork',
    category: '地图服务',
    source: 'market',
    description: '读取 3D Tiles 服务信息，检查 tileset 层级、包围盒和元数据。',
    version: 'v1.0.1',
    transport: 'http',
    downloads: '12.9K',
    connected: false,
    enabled: false,
    status: 'not-connected',
    tags: ['Cesium', '3D Tiles', 'tileset'],
    tools: ['inspect_tileset', 'summarize_tiles'],
  },
  {
    id: 'spatial-file-system',
    name: '本地空间文件系统',
    slug: 'spatial-file-system',
    author: '@GeoWork',
    category: '文件系统',
    source: 'market',
    description: '读取工作目录中的 GeoJSON、Shapefile、CSV、DEM 和影像文件摘要。',
    version: 'v1.0.0',
    transport: 'stdio',
    downloads: '11.8K',
    connected: false,
    enabled: false,
    status: 'not-connected',
    tags: ['文件系统', 'GeoJSON', 'Shapefile'],
    tools: ['list_spatial_files', 'describe_dataset', 'read_metadata'],
  },
  {
    id: 'remote-index-service',
    name: '遥感指数计算服务',
    slug: 'remote-index-service',
    author: '@GeoWork',
    category: '遥感平台',
    source: 'market',
    description: '计算 NDVI、NDWI、NDBI 等遥感指数，并返回统计摘要。',
    version: 'v1.1.0',
    transport: 'http',
    downloads: '10.5K',
    connected: false,
    enabled: false,
    status: 'not-connected',
    tags: ['NDVI', '遥感指数', '统计'],
    tools: ['calculate_index', 'summarize_index'],
  },
  {
    id: 'map-export-service',
    name: '地图导出服务',
    slug: 'map-export-service',
    author: '@GeoWork',
    category: '自动报告',
    source: 'market',
    description: '导出地图快照、图例、比例尺和图层说明，用于报告生成。',
    version: 'v1.0.0',
    transport: 'http',
    downloads: '9.3K',
    connected: false,
    enabled: false,
    status: 'not-connected',
    tags: ['地图导出', '图例', '报告'],
    tools: ['export_map', 'export_legend'],
  },
  {
    id: 'spatial-report-mcp',
    name: '空间报告生成器',
    slug: 'spatial-report-mcp',
    author: '@GeoWork',
    category: '自动报告',
    source: 'market',
    description: '将分析过程、工具调用结果和地图图层整理成 Markdown 报告。',
    version: 'v1.0.0',
    transport: 'http',
    downloads: '8.6K',
    connected: false,
    enabled: false,
    status: 'not-connected',
    tags: ['报告生成', 'Markdown', '分析摘要'],
    tools: ['create_report', 'append_map_summary'],
  },
]

/* ── 内置 MCP（8个） ── */

export const builtInMcpServers: McpServerItem[] = [
  {
    id: 'geowork-files',
    name: 'GeoWork 文件管理',
    slug: 'geowork-files',
    author: '@GeoWork',
    category: '文件系统',
    source: 'built-in',
    description: '读取当前工作目录中的文件摘要和空间数据清单。',
    version: 'v1.0.0',
    transport: 'stdio',
    connected: true,
    enabled: true,
    status: 'connected',
    tags: ['文件', '工作目录'],
    tools: ['list_files', 'describe_file', 'read_summary'],
  },
  {
    id: 'geowork-memory',
    name: 'GeoWork 记忆',
    slug: 'geowork-memory',
    author: '@GeoWork',
    category: '开发工具',
    source: 'built-in',
    description: '读取 GeoWork 本地记忆、任务上下文和最近工作流摘要。',
    version: 'v1.0.0',
    transport: 'stdio',
    connected: true,
    enabled: true,
    status: 'connected',
    tags: ['记忆', '上下文'],
    tools: ['read_memory', 'list_tasks', 'workflow_summary'],
  },
  {
    id: 'geowork-tasks',
    name: 'GeoWork 任务',
    slug: 'geowork-tasks',
    author: '@GeoWork',
    category: '开发工具',
    source: 'built-in',
    description: '读取定时任务、执行记录和任务状态。',
    version: 'v1.0.0',
    transport: 'stdio',
    connected: true,
    enabled: true,
    status: 'connected',
    tags: ['任务', '定时'],
    tools: ['list_tasks', 'task_status', 'execution_log'],
  },
  {
    id: 'geowork-map-context',
    name: 'GeoWork 地图上下文',
    slug: 'geowork-map-context',
    author: '@GeoWork',
    category: '地图服务',
    source: 'built-in',
    description: '读取当前地图视图、图层列表和选中要素。',
    version: 'v1.0.0',
    transport: 'stdio',
    connected: true,
    enabled: true,
    status: 'connected',
    tags: ['地图', '视图', '图层'],
    tools: ['get_view', 'list_layers', 'selected_features'],
  },
  {
    id: 'geowork-data-center',
    name: 'GeoWork 数据中心',
    slug: 'geowork-data-center',
    author: '@GeoWork',
    category: '数据库',
    source: 'built-in',
    description: '读取数据中心中的数据集、字段和元信息。',
    version: 'v1.0.0',
    transport: 'stdio',
    connected: true,
    enabled: true,
    status: 'connected',
    tags: ['数据', '元信息'],
    tools: ['list_datasets', 'describe_fields', 'metadata'],
  },
  {
    id: 'geowork-report',
    name: 'GeoWork 报告',
    slug: 'geowork-report',
    author: '@GeoWork',
    category: '自动报告',
    source: 'built-in',
    description: '生成 Markdown 报告和空间分析摘要。',
    version: 'v1.0.0',
    transport: 'stdio',
    connected: true,
    enabled: true,
    status: 'connected',
    tags: ['报告', 'Markdown'],
    tools: ['generate_report', 'analysis_summary'],
  },
  {
    id: 'geowork-remote-sensing',
    name: 'GeoWork 遥感',
    slug: 'geowork-remote-sensing',
    author: '@GeoWork',
    category: '遥感平台',
    source: 'built-in',
    description: '读取遥感影像元信息、波段和指数计算配置。',
    version: 'v1.0.0',
    transport: 'stdio',
    connected: true,
    enabled: true,
    status: 'connected',
    tags: ['遥感', '波段', '指数'],
    tools: ['image_metadata', 'band_info', 'index_config'],
  },
  {
    id: 'geowork-tools',
    name: 'GeoWork 工具',
    slug: 'geowork-tools',
    author: '@GeoWork',
    category: '开发工具',
    source: 'built-in',
    description: '提供 GeoWork 内置空间分析工具清单。',
    version: 'v1.0.0',
    transport: 'stdio',
    connected: true,
    enabled: true,
    status: 'connected',
    tags: ['工具', '空间分析'],
    tools: ['list_tools', 'tool_description', 'run_tool'],
  },
]
