export type SkillCategory =
  | '空间分析'
  | '遥感解译'
  | '数据处理'
  | '专题制图'
  | '数据质检'
  | '自动报告'

export type SkillSource = 'market' | 'built-in' | 'local'

export type SkillItem = {
  id: string
  name: string
  slug: string
  author: string
  category: SkillCategory
  source: SkillSource
  description: string
  version: string
  downloads?: string
  installed: boolean
  enabled: boolean
  featured?: boolean
  tags: string[]
}

export const skillCategories = [
  '全部',
  '空间分析',
  '遥感解译',
  '数据处理',
  '专题制图',
  '数据质检',
  '自动报告',
] as const

/* ══════════════ 市场技能 (12) ══════════════ */

export const marketSkills: SkillItem[] = [
  {
    id: 'buffer-analysis',
    name: '缓冲区分析',
    slug: 'buffer-analysis',
    author: '@GeoWork',
    category: '空间分析',
    source: 'market',
    description: '根据点、线、面要素生成缓冲区，并输出范围统计和图层摘要。',
    version: 'v1.2.0',
    downloads: '28.3K',
    installed: false,
    enabled: false,
    featured: true,
    tags: ['GIS', 'Buffer', 'GeoJSON'],
  },
  {
    id: 'overlay-analysis',
    name: '叠加分析',
    slug: 'overlay-analysis',
    author: '@GeoWork',
    category: '空间分析',
    source: 'market',
    description: '执行相交、裁剪、合并等空间叠加操作，生成可追溯分析结果。',
    version: 'v1.1.0',
    downloads: '21.8K',
    installed: false,
    enabled: false,
    tags: ['GIS', 'Overlay', 'Clip'],
  },
  {
    id: 'crs-transform',
    name: '坐标系转换',
    slug: 'crs-transform',
    author: '@GeoWork',
    category: '数据处理',
    source: 'market',
    description: '识别并转换常见坐标系统，检查数据投影与地图底图是否一致。',
    version: 'v1.0.3',
    downloads: '18.6K',
    installed: false,
    enabled: false,
    tags: ['CRS', 'EPSG', '投影'],
  },
  {
    id: 'geojson-field-cleaner',
    name: 'GeoJSON 字段清洗',
    slug: 'geojson-field-cleaner',
    author: '@GeoWork',
    category: '数据质检',
    source: 'market',
    description: '检查属性字段缺失、重复、类型不一致和异常值，输出清洗建议。',
    version: 'v1.0.1',
    downloads: '15.2K',
    installed: false,
    enabled: false,
    tags: ['GeoJSON', '字段', '质检'],
  },
  {
    id: 'shapefile-importer',
    name: 'Shapefile 导入助手',
    slug: 'shapefile-importer',
    author: '@GeoWork',
    category: '数据处理',
    source: 'market',
    description: '辅助导入 Shapefile 数据，检查编码、投影文件和字段兼容性。',
    version: 'v1.0.2',
    downloads: '13.7K',
    installed: false,
    enabled: false,
    tags: ['Shapefile', '导入', '编码'],
  },
  {
    id: 'ndvi-calculator',
    name: 'NDVI 计算',
    slug: 'ndvi-calculator',
    author: '@GeoWork',
    category: '遥感解译',
    source: 'market',
    description: '根据多光谱影像波段生成 NDVI 指数，并输出植被覆盖摘要。',
    version: 'v1.3.0',
    downloads: '12.4K',
    installed: false,
    enabled: false,
    featured: true,
    tags: ['NDVI', '遥感', '植被'],
  },
  {
    id: 'remote-change-detection',
    name: '遥感变化检测',
    slug: 'remote-change-detection',
    author: '@GeoWork',
    category: '遥感解译',
    source: 'market',
    description: '对比多期遥感影像，标记变化区域并生成面积统计。',
    version: 'v1.1.0',
    downloads: '11.9K',
    installed: false,
    enabled: false,
    tags: ['变化检测', '遥感', '多期影像'],
  },
  {
    id: 'dem-terrain-analysis',
    name: 'DEM 坡度坡向',
    slug: 'dem-terrain-analysis',
    author: '@GeoWork',
    category: '空间分析',
    source: 'market',
    description: '基于 DEM 计算坡度、坡向和地形因子，支持地形分析报告。',
    version: 'v1.0.0',
    downloads: '9.8K',
    installed: false,
    enabled: false,
    tags: ['DEM', '坡度', '坡向'],
  },
  {
    id: 'thematic-map-maker',
    name: '专题图制图',
    slug: 'thematic-map-maker',
    author: '@GeoWork',
    category: '专题制图',
    source: 'market',
    description: '根据业务指标生成专题图建议、图例规范和出图说明。',
    version: 'v1.0.1',
    downloads: '8.7K',
    installed: false,
    enabled: false,
    tags: ['专题图', '图例', '制图'],
  },
  {
    id: 'map-report-generator',
    name: '地图报告生成',
    slug: 'map-report-generator',
    author: '@GeoWork',
    category: '自动报告',
    source: 'market',
    description: '将地图分析过程、图层摘要和关键结论整理成 Markdown 报告。',
    version: 'v1.0.0',
    downloads: '7.5K',
    installed: false,
    enabled: false,
    tags: ['报告', 'Markdown', '摘要'],
  },
  {
    id: 'spatial-data-validator',
    name: '空间数据质检',
    slug: 'spatial-data-validator',
    author: '@GeoWork',
    category: '数据质检',
    source: 'market',
    description: '检查几何有效性、坐标范围、重复要素和字段完整性。',
    version: 'v1.1.2',
    downloads: '6.9K',
    installed: false,
    enabled: false,
    tags: ['质检', '几何', '拓扑'],
  },
  {
    id: 'poi-accessibility',
    name: 'POI 可达性分析',
    slug: 'poi-accessibility',
    author: '@GeoWork',
    category: '空间分析',
    source: 'market',
    description: '基于 POI 和路网距离估算服务覆盖范围，辅助选址与规划。',
    version: 'v1.0.0',
    downloads: '5.8K',
    installed: false,
    enabled: false,
    tags: ['POI', '可达性', '选址'],
  },
]

/* ══════════════ 内置技能 (8) ══════════════ */

export const builtInSkills: SkillItem[] = [
  {
    id: 'builtin-csv',
    name: 'CSV 解析',
    slug: 'csv',
    author: '@GeoWork',
    category: '数据处理',
    source: 'built-in',
    description: '读取、预览和清洗 CSV 表格数据。',
    version: 'v1.0.0',
    installed: true,
    enabled: true,
    tags: ['CSV', '表格'],
  },
  {
    id: 'builtin-geojson',
    name: 'GeoJSON 解析',
    slug: 'geojson',
    author: '@GeoWork',
    category: '数据处理',
    source: 'built-in',
    description: '解析 GeoJSON 要素、字段和几何类型。',
    version: 'v1.0.0',
    installed: true,
    enabled: true,
    tags: ['GeoJSON', '要素'],
  },
  {
    id: 'builtin-raster-preview',
    name: '栅格影像预览',
    slug: 'raster-preview',
    author: '@GeoWork',
    category: '遥感解译',
    source: 'built-in',
    description: '预览栅格影像元信息和波段摘要。',
    version: 'v1.0.0',
    installed: true,
    enabled: true,
    tags: ['栅格', '影像', '波段'],
  },
  {
    id: 'builtin-pdf',
    name: 'PDF 读取',
    slug: 'pdf',
    author: '@GeoWork',
    category: '自动报告',
    source: 'built-in',
    description: '读取 PDF 文档中的文本和表格摘要。',
    version: 'v1.0.0',
    installed: true,
    enabled: true,
    tags: ['PDF', '文档'],
  },
  {
    id: 'builtin-docx',
    name: 'Word 读取',
    slug: 'docx',
    author: '@GeoWork',
    category: '自动报告',
    source: 'built-in',
    description: '读取 Word 文档并生成结构化摘要。',
    version: 'v1.0.0',
    installed: true,
    enabled: true,
    tags: ['Word', '文档'],
  },
  {
    id: 'builtin-xlsx',
    name: 'Excel 读取',
    slug: 'xlsx',
    author: '@GeoWork',
    category: '数据处理',
    source: 'built-in',
    description: '读取 Excel 表格、工作表和字段信息。',
    version: 'v1.0.0',
    installed: true,
    enabled: true,
    tags: ['Excel', '表格'],
  },
  {
    id: 'builtin-markdown',
    name: 'Markdown 整理',
    slug: 'markdown',
    author: '@GeoWork',
    category: '自动报告',
    source: 'built-in',
    description: '生成和整理 Markdown 分析报告。',
    version: 'v1.0.0',
    installed: true,
    enabled: true,
    tags: ['Markdown', '报告'],
  },
  {
    id: 'builtin-map-export',
    name: '地图导出',
    slug: 'map-export',
    author: '@GeoWork',
    category: '专题制图',
    source: 'built-in',
    description: '导出地图截图、图层说明和制图摘要。',
    version: 'v1.0.0',
    installed: true,
    enabled: true,
    tags: ['导出', '截图', '制图'],
  },
]
