# GeoWork Python Worker - Office Document Generation

"""Office document generation module for GeoWork reports and presentations."""

from typing import Any


def write_report(
    title: str = "GeoWork Report",
    prompt: str = "",
    mode: str = "Analysis",
    artifacts: list[dict[str, Any]] | None = None,
) -> dict[str, Any]:
    """Generate a Markdown report with optional DOCX output."""
    markdown = f"""# {title}

## Prompt

{prompt or "GeoWork analysis task"}

## Mode

{mode}

## Artifacts

"""
    if artifacts:
        for art in artifacts:
            markdown += f"- {art.get('name', 'Unknown')} ({art.get('type', 'unknown')})\n"
    else:
        markdown += "- No artifacts generated\n"

    markdown += """
## Reproducibility

All file writes were scoped to the project workspace.
"""
    return {
        "ok": True,
        "markdown": markdown,
        "artifacts": [
            {"name": "Markdown Report", "type": "report", "mimeType": "text/markdown"},
        ],
    }


def write_presentation(
    title: str = "GeoWork Analysis",
    sections: list[str] | None = None,
) -> dict[str, Any]:
    """Generate a PowerPoint presentation.

    Uses python-pptx to create a real .pptx file with structured slides.
    """
    try:
        from pptx import Presentation
        from pptx.util import Inches
        import os
        import tempfile

        slides = sections or ["Objective", "Data", "Workflow", "Results", "Reproducibility"]

        # Create a temporary presentation
        prs = Presentation()

        # Title slide
        slide_layout = prs.slide_layouts[0]  # Title slide layout
        slide = prs.slides.add_slide(slide_layout)
        slide.shapes.title.text = title
        slide.placeholders[1].text = f"Generated by GeoWork — {title}"

        # Content slides
        for section in slides:
            slide_layout = prs.slide_layouts[1]  # Title and Content layout
            slide = prs.slides.add_slide(slide_layout)
            slide.shapes.title.text = section
            slide.placeholders[1].text = f"Section: {section}"

        # Save to a temporary location and return metadata
        tmp_dir = tempfile.gettempdir()
        output_path = os.path.join(tmp_dir, f"{title.replace(' ', '_')}.pptx")
        prs.save(output_path)

        return {
            "ok": True,
            "message": f"Presentation saved to {output_path}",
            "output_path": output_path,
            "slide_count": len(prs.slides),
            "slides": [{"title": s.shapes.title.text if s.shapes.title else "Untitled"} for s in prs.slides],
            "artifacts": [
                {"name": "PowerPoint Presentation", "type": "presentation", "mimeType": "application/vnd.openxmlformats-officedocument.presentationml.presentation", "path": output_path},
            ],
        }
    except ImportError:
        return {
            "ok": True,
            "message": "python-pptx not installed — returning metadata only",
            "slides": [{"title": title}] + [{"title": s} for s in slides],
            "artifacts": [
                {"name": "PowerPoint Presentation", "type": "presentation", "mimeType": "application/vnd.openxmlformats-officedocument.presentationml.presentation"},
            ],
            "hint": "Install python-pptx to generate actual .pptx files: pip install python-pptx",
        }


def write_spreadsheet(
    title: str = "GeoWork Statistics",
    data: list[list[Any]] | None = None,
) -> dict[str, Any]:
    """Generate an Excel workbook."""
    rows = data or [["metric", "value"], ["task_status", "completed"], ["mode", "Analysis"]]
    return {
        "ok": True,
        "message": "Excel workbook generated (placeholder)",
        "rows": rows,
        "artifacts": [
            {"name": "Excel Workbook", "type": "spreadsheet", "mimeType": "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"},
        ],
    }


def write_notebook(
    title: str = "GeoWork Workflow",
    prompt: str = "",
    cells: list[dict[str, Any]] | None = None,
) -> dict[str, Any]:
    """Generate a Jupyter Notebook."""
    if cells is None:
        cells = [
            {"cell_type": "markdown", "source": [f"# {title}\n", prompt]},
            {"cell_type": "code", "source": ["print('GeoWork task completed')"]},
        ]
    return {
        "ok": True,
        "message": "Jupyter Notebook generated (placeholder)",
        "cells": cells,
        "artifacts": [
            {"name": "Jupyter Notebook", "type": "notebook", "mimeType": "application/x-ipynb+json"},
        ],
    }
